E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('products.urls')),
    path('cart/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL, 
            document_root=settings.MEDIA_ROOT
    )

products/urls.py
from django.urls import path
from .views import ProductListView
from products import views

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('<str:id>', views.filter, name='filter'),
    path('<str:text>', views.search, name='search'),
    path('add/', views.add, name='add'),
    path('add-to-cart/<int:pk>/<int:quantity>', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

users/urls.py
from django.urls import path
from users import views

from django.contrib.auth.views import (
    LoginView,
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),

    path('login/', LoginView.as_view(template_name='users/log_in.html', ), name='login'),

    path('logout/', views.log_out, name='logout'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/reset_password/reset_password.html', html_email_template_name='users/reset_password/reset_password_email.html'), name='password-reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/reset_password/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='users/reset_password/password_reset_complete.html'), name='password_reset_complete'),
]

products/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='product_image/', null=True, blank=True)

    def save(self, *args, **kwargs):
        # Update the image name based on the product name
        if self.image:
            extension = self.image.name.split('.')[-1]
            new_name = slugify(self.name)  # Using slugify to create a valid filename
            self.image.name = f'{new_name}.{extension}'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Write the title', 'tabindex':'4'}),
            'description': forms.Textarea(attrs={'class': 'form-control w-250', 'placeholder': 'Write the description', 'tabindex':'5'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'min': '100', 'step': '100', 'placeholder': 'Enter the price', 'tabindex':'6'}),
            'image': forms.ClearableFileInput(attrs={'class': 'custom-file-input', 'tabindex':'7'})
        }

products/views.py
from django.views.generic import ListView
from orders.models import Order
from products.forms import ProductForm
from .models import Product
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.admin.views.decorators import staff_member_required

class ProductListView(ListView):
    model = Product
    template_name = 'products/home.html'
    context_object_name = 'products'

def search(request):
    text = request.GET.get('text')

    if text:
        products = Product.objects.filter(name__icontains=text)
    else:
        products = Product.objects.none()
    
    return render(request, 'products/search_results.html', {'products': products})

def filter(request, id):
    # Define a dictionary mapping filter keys to filter functions
    filters = {
        'ase': ascending_name,
        'dec': descending_name,
        'barato': ascending_price,
        'caro': descending_price,
    }

    # Get the filter function corresponding to the given attribute
    filter_func = filters.get(id)

    if filter_func:
        products = filter_func()

    else:
        products = Product.objects.all()

    return render(request, 'products/home.html', {'products': products})

def ascending_name():
    return Product.objects.all().order_by('name')

def descending_name():
    return Product.objects.all().order_by('-name')

def ascending_price():
    return Product.objects.all().order_by('price')

def descending_price():
    return Product.objects.all().order_by('-price')


# Only can create articles the admins.
@staff_member_required
def detail(request, pk):
    if request.method == 'GET':
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(instance=product)
        return render(request, 'products/detail.html', {'product': product, 'form': form})

@staff_member_required
def add(request):
    if request.method == 'GET':
        return render(request, 'products/add.html', {
            'form': ProductForm
        })
    
    elif request.method == 'POST':
        try:
            form = ProductForm(request.POST, request.FILES)
            new_product = form.save(commit = False)
            new_product.user = request.user
            if form.is_valid():
                form.save()
                return redirect('products:home')

        except ValueError:
            return render(request, 'products/add.html', {
                'form': ProductForm,
                'error': "Please provide valid data"
            })
        
def add_to_cart(request, pk, quantity):
    product = get_object_or_404(Product, pk=pk)

    # Check if the user already has an active order, create one if not
    order, created = Order.objects.get_or_create(user=request.user, product=product, defaults={'quantity': quantity})

    if not created:
        order.quantity += int(quantity)
        order.save()

    return redirect('products:home')

@staff_member_required
def update(request, pk):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()
            return redirect('products:home')

@staff_member_required
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        product.delete()

    return redirect('products:home')

templates/products/add.html
{% extends 'base.html' %}

{% block title %}Add Product{% endblock %}

{% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 pt-5">
      <form
        action="{% url 'products:add' %}"
        method="POST"
        class="card card-body"
        enctype="multipart/form-data"
      >
        <h1 class="text-center">Add Product</h1>
 
        {{error}} {% csrf_token %} {{form.as_p}}

        <button class="btn btn-success" type="submit" tabindex="8">Save</button>
      </form>
    </div>
  </div>
</main>

{% endblock%}

templates/products/detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5 mb-5">
      <h1 class="text-secondary text-center">{{ product.name }}</h1>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ e }} {{form.as_p}}

        <div class="d-flex justify-content-between">
          <button
            class="btn btn-primary"
            formaction="{% url 'products:update' product.id %}"
            formmethod="post"
            type="submit"
            tabindex="8"
          >
            Update
          </button>

          <button
            class="btn btn-danger"
            formaction="{% url 'products:delete' product.id %}"
            formmethod="post"
            type="submit"
            tabindex="9"
          >
            Delete
          </button>
        </div>
      </form>
    </div>
  </div>
</main>

{% endblock%}

templates/products/home.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% load static %}
{% load humanize %}

{% block content %}

<main class="container mt-5">
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    rel="stylesheet"
  />
  <script src="{% static 'js/add_to_cart.js' %}"></script>
  <script src="{% static 'js/getValue.js' %}"></script>
  <script src="{% static 'js/search.js' %}"></script>

  <article class="row justify-content-center">
    <section class="col-lg-3 col-md-4 col-sm-6">
      <div class="bg-light p-3 rounded">
        <h2 class="mb-3">Filters</h2>

        <!-- Search Bar -->
        <div class="input-group mb-3">
          <input
            type="search"
            class="form-control rounded"
            placeholder="Search"
            aria-label="Buscar"
            aria-describedby="search-addon"
            id="searchBar"
            tabindex="4"
          />

          <button
            type="submit"
            class="btn btn-primary"
            onclick="searchProduct()"
            tabindex="5"
          >
            <i class="fas fa-search"></i>
          </button>
        </div>

        <!-- Filters List -->
        <ul class="list-group">
          <li class="list-group-item">
            <div class="form-check">
              <input
                class="form-check-input"
                type="radio"
                name="filter"
                id="dec"
                onclick="getValue()"
              />
              <label class="form-check-label" for="dec"> A-Z </label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-check">
              <input
                class="form-check-input"
                type="radio"
                name="filter"
                id="ase"
                onclick="getValue()"
              />
              <label class="form-check-label" for="ase"> Z-A </label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-check">
              <input
                class="form-check-input"
                type="radio"
                name="filter"
                id="barato"
                onclick="getValue()"
              />
              <label class="form-check-label" for="barato">
                More cheap
              </label>
            </div>
          </li>
          <li class="list-group-item">
            <div class="form-check">
              <input
                class="form-check-input"
                type="radio"
                name="filter"
                id="caro"
                onclick="getValue()"
              />
              <label class="form-check-label" for="caro">
                More expensive
              </label>
            </div>
          </li>
        </ul>        
      </div>
    </section>

    <section class="col-md-8">
      <div class="card card-body">
        <div class="row align-items-center mb-3">
          <h1 class="col card-title text-center">Product list</h1>

          {% if user.is_staff %}
          <button
            class="btn btn-success col-2 m-2"
            onclick="window.location.href=`{% url 'products:add' %}`"
            tabindex="10">
            Add
          </button>
          {% endif %}
        </div>

        <ul class="list-group list-group-flush">
          {% for product in products %}
          <li class="list-group-item">
            <div class="row align-items-center">
              <div class="col-md-4">
                <img
                  loading="lazy"
                  class="img-fluid"
                  src="/media/{{ product.image.name }}"
                  alt="{{ product.name }}"
                />
              </div>

              <div class="col-md-8">
                <header class="mb-3">
                  <a
                    href="{% url 'products:detail' product.id %}"
                    class="text-decoration-none"
                    tabindex="-1"
                  >
                    <h2 class="font-weight-bold mb-0">{{ product.name }}</h2>
                  </a>
                  <p>{{ product.description }}</p>
                </header>

                <span class="mb-2">₡ {{ product.price | floatformat | intcomma }}</span>

                {% if user.is_authenticated %}
                <footer class="mt-3">
                  <div class="row align-items-center">
                    <div class="col-sm-6 mb-2 mb-sm-0">
                      <input
                        class="form-control"
                        type="number"
                        id="input{{ product.id }}"
                        min="0"
                        step="1"
                        placeholder="Select the quantity"
                        tabindex="11"
                        required
                      />
                    </div>
                
                    <div class="col-sm-6 text-sm-end">
                      <div class="btn-group" role="group" aria-label="Add to cart buttons">
                        <button
                          class="btn btn-secondary"
                          type="button"
                          onclick="addToCart('{{ product.id }}')"
                          tabindex="12"
                        >
                          Add to cart
                        </button>
                
                        {% if user.is_staff %}
                        <a
                          href="{% url 'products:detail' product.id %}"
                          class="btn btn-primary ms-2"
                          tabindex="13"
                        >
                          Details
                        </a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </footer>
                
                {% endif %}
              </div>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </section>
  </article>
</main>

{% endblock %}