E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('products.urls')),
    path('cart/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL, 
            document_root=settings.MEDIA_ROOT
    )

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('delete/<int:pk>', views.delete, name='delete')
]

products/urls.py
from django.urls import path
from .views import ProductListView
from products import views

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('<str:id>', views.filter, name='filter'),
    path('<str:text>', views.search, name='search'),
    path('add/', views.add, name='add'),
    path('add-to-cart/<int:pk>/<int:quantity>', views.add_to_cart, name='add_to_cart'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

users/urls.py
from django.urls import path
from users import views

from django.contrib.auth.views import (
    LoginView,
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),

    path('login/', LoginView.as_view(template_name='users/log_in.html', ), name='login'),

    path('logout/', views.log_out, name='logout'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/reset_password/reset_password.html', html_email_template_name='users/reset_password/reset_password_email.html'), name='password-reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/reset_password/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='users/reset_password/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
 
    <title>{% block title %}My E-commerce{% endblock %}</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'products:home' %}">Home</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
            tabindex="1"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}" tabindex="2">
                  Log out
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'orders:cart' %}" tabindex="3">
                  Cart
                </a>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}" tabindex="2">
                  Register
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}" tabindex="3">
                  Log in
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    {% block content %}
    <!-- Content goes here -->
    {% endblock %}
  </body>
</html>