E_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('products.urls')),
    path('cart/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL, 
            document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.urls import path
from users import views

from django.contrib.auth.views import (
    LoginView,
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),

    path('login/', LoginView.as_view(template_name='users/log_in.html', ), name='login'),

    path('logout/', views.log_out, name='logout'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/reset_password/reset_password.html', html_email_template_name='users/reset_password/reset_password_email.html'), name='password-reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/reset_password/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='users/reset_password/password_reset_complete.html'), name='password_reset_complete'),
]

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.shortcuts import redirect, render

# import logging

# Create your views here.
def log_out(request):
    logout(request)
    return redirect('products:home')

def register(request):
    if request.method == 'GET':
        return render(request, 'users/register.html', {
            'form': UserCreationForm
        })
    
    elif request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            # Move this block of code to querys class
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return render(request, 'products/home.html')

            except:
                return render(request, 'users/register.html', {
                    'form': UserCreationForm,
                    'error': "User already exist"
                })
        else:
            return render(request, 'users/register.html', {
                'form': UserCreationForm,
                'error': "Password do not match"
            })

templates/users/log_in.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
      <form
        action="{% url 'users:login' %}"
        method="POST"
        class="card card-body"
      >
        <h1 class="text-center">Log in</h1>
 
        {{error}} {% csrf_token %}

        <div class="mb-3">
          <label for="username">Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            class="form-control"
            tabindex="4"
            placeholder="Write your username."
          />
        </div>

        <div class="mb-3">
          <label for="password">Password: </label>
          <input
            type="password"
            name="password"
            id="password"
            class="form-control"
            tabindex="5"
            placeholder="Write your password."
          />
          <a href="{% url 'users:password-reset' %}">Reset password</a>
        </div>
        <button class="btn btn-dark" type="submit" tabindex="6">Submit</button>
      </form>
    </div>
  </div>
</main>

{% endblock%}

templates/users/register.html
{% extends 'base.html' %} 

{% block title %}Register{% endblock %} 

{% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-5">
      <form
        action="{% url 'users:register' %}"
        method="POST"
        class="card card-body"
      >
        <h1 class="text-center">Register</h1>
 
        {{error}} {% csrf_token %}

        <div class="mb-3">
          <label for="username"> Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            class="form-control"
            tabindex="4"
            placeholder="Write your username."
          />
        </div>

        <div class="mb-3">
          <label for="password1"> Password: </label>
          <input
            type="password"
            name="password1"
            id="password1"
            class="form-control"
            tabindex="5"
            placeholder="Write your password."
          />
        </div>

        <div class="mb-3">
          <label for="password2"> Confirm password: </label>
          <input
            type="password"
            name="password2"
            id="password2"
            class="form-control"
            tabindex="6"
            placeholder="Confirm your password."
          />
        </div>

        <button class="btn btn-dark" type="submit" tabindex="7">Submit</button>
      </form>
    </div>
  </div>
</main>

{% endblock%}